// Generated from chapter1_story_최종본.zip.
// Existing final-story files are mapped 1:1 by filename; only explicit source aliases use canonical game assets.
export const CHAPTER1_STORY_ASSETS: Readonly<Record<string, string>> = {
  "bg_academic_system_corrupted.png": "/assets/story/chapter1/backgrounds/bg_academic_system_corrupted.png",
  "bg_academic_system_purified.png": "/assets/story/chapter1/backgrounds/bg_academic_system_purified.png",
  "bg_attendance_drone_story.png": "/assets/story/chapter1/backgrounds/bg_attendance_drone_story.png",
  "bg_attendance_escape_run_corridor.png": "/assets/story/chapter1/backgrounds/bg_attendance_escape_run_corridor.png",
  "bg_attendance_escape_story.png": "/assets/story/chapter1/backgrounds/bg_attendance_escape_story.png",
  "bg_black.png": "/assets/story/chapter1/effects/bg_black.svg",
  "bg_boss_entrance_closed.png": "/assets/story/chapter1/backgrounds/bg_boss_entrance_closed.png",
  "bg_boss_entrance_open.png": "/assets/story/chapter1/backgrounds/bg_boss_entrance_open.png",
  "bg_knu_admission_post.png": "/assets/story/chapter1/backgrounds/bg_knu_admission_post.png",
  "bg_knu_campus.png": "/assets/story/chapter1/backgrounds/bg_knu_admission_post.png",
  "bg_knu_main_building_story21.png": "/assets/story/chapter1/backgrounds/bg_knu_admission_post.png",
  "bg_login_watcher_story.png": "/assets/story/chapter1/backgrounds/bg_login_watcher_story.png",
  "bg_notice_drone_story.png": "/assets/story/chapter1/backgrounds/bg_notice_drone_story.png",
  "bg_prologue_void.svg": "/assets/story/chapter1/effects/bg_prologue_void.svg",
  "bg_room_distorter_story.png": "/assets/story/chapter1/backgrounds/bg_room_distorter_story.png",
  "bg_server_core_clean.png": "/assets/story/chapter1/backgrounds/bg_academic_system_purified.png",
  "bg_server_core_corrupt.png": "/assets/story/chapter1/backgrounds/bg_academic_system_corrupted.png",
  "bg_server_gate_closed.png": "/assets/story/chapter1/backgrounds/bg_boss_entrance_closed.png",
  "bg_server_gate_open.png": "/assets/story/chapter1/backgrounds/bg_boss_entrance_open.png",
  "boss_gatekeeper_phase1_transparent.png": "/assets/story/chapter1/characters/boss_gatekeeper_phase1_transparent.png",
  "boss_gatekeeper_purified_transparent.png": "/assets/chapter1/boss/body/gatekeeper_purified.webp",
  "boss_gatekeeper_uploaded.png": "/assets/story/chapter1/characters/boss_gatekeeper_uploaded.png",
  "character_hobanwoo.svg": "/assets/story/chapter1/characters/hobanwoo_pose_neutral.png",
  "frame_knu_default.svg": "/assets/story/chapter1/ui/frame_knu_default.svg",
  "game_logo.png": "/assets/story/chapter1/ui/game_logo.png",
  "hobanwoo_pose_angry.png": "/assets/story/chapter1/characters/hobanwoo_pose_angry.png",
  "hobanwoo_pose_battle_ready.png": "/assets/story/chapter1/characters/hobanwoo_pose_battle_ready.png",
  "hobanwoo_pose_cautious_resolve.png": "/assets/story/chapter1/characters/hobanwoo_pose_cautious_resolve.png",
  "hobanwoo_pose_confident_present.png": "/assets/story/chapter1/characters/hobanwoo_pose_confident_present.png",
  "hobanwoo_pose_crying.png": "/assets/story/chapter1/characters/hobanwoo_pose_crying.png",
  "hobanwoo_pose_down.png": "/assets/story/chapter1/characters/hobanwoo_pose_down.png",
  "hobanwoo_pose_explaining.png": "/assets/story/chapter1/characters/hobanwoo_pose_explaining.png",
  "hobanwoo_pose_expressionless.png": "/assets/story/chapter1/characters/hobanwoo_pose_expressionless.png",
  "hobanwoo_pose_fierce_battle.png": "/assets/story/chapter1/characters/hobanwoo_pose_fierce_battle.png",
  "hobanwoo_pose_flustered.png": "/assets/story/chapter1/characters/hobanwoo_pose_flustered.png",
  "hobanwoo_pose_neutral.png": "/assets/story/chapter1/characters/hobanwoo_pose_neutral.png",
  "hobanwoo_pose_point.png": "/assets/story/chapter1/characters/hobanwoo_pose_point.png",
  "hobanwoo_pose_sad.png": "/assets/story/chapter1/characters/hobanwoo_pose_sad.png",
  "hobanwoo_pose_serious_brave.png": "/assets/story/chapter1/characters/hobanwoo_pose_serious_brave.png",
  "hobanwoo_pose_shocked.png": "/assets/story/chapter1/characters/hobanwoo_pose_shocked.png",
  "hobanwoo_pose_shy.png": "/assets/story/chapter1/characters/hobanwoo_pose_shy.png",
  "hobanwoo_pose_sleepy.png": "/assets/story/chapter1/characters/hobanwoo_pose_sleepy.png",
  "hobanwoo_pose_sparkle.png": "/assets/story/chapter1/characters/hobanwoo_pose_sparkle.png",
  "hobanwoo_pose_surprised.png": "/assets/story/chapter1/characters/hobanwoo_pose_surprised.png",
  "hobanwoo_pose_thinking.png": "/assets/story/chapter1/characters/hobanwoo_pose_thinking.png",
  "hobanwoo_pose_troubled_crossed.png": "/assets/story/chapter1/characters/hobanwoo_pose_troubled_crossed.png",
  "hobanwoo_pose_wary.png": "/assets/story/chapter1/characters/hobanwoo_pose_wary.png",
  "hobanwoo_pose_wave.png": "/assets/story/chapter1/characters/hobanwoo_pose_wave.png",
  "hobanwoo_pose_worried.png": "/assets/story/chapter1/characters/hobanwoo_pose_worried.png",
  "monster_01_attendance_drone.png": "/assets/story/chapter1/characters/monster_01_attendance_drone.png",
  "monster_02_absence_drone.png": "/assets/chapter1/waves/enemies/monster_02_absence.png",
  "monster_03_notice_drone.png": "/assets/story/chapter1/characters/monster_03_notice_drone.png",
  "monster_04_student_terminal.png": "/assets/story/chapter1/characters/monster_04_student_terminal.png",
  "monster_05_login_watcher.png": "/assets/story/chapter1/characters/monster_05_login_watcher.png",
  "monster_06_course_guide_bug.png": "/assets/chapter1/waves/enemies/monster_06_course_bug.png",
  "monster_07_timetable_block.png": "/assets/chapter1/waves/enemies/monster_07_schedule_block.png",
  "monster_08_seat_drone.png": "/assets/chapter1/waves/enemies/monster_08_seat_drone.png",
  "monster_09_cart_box.png": "/assets/chapter1/waves/enemies/monster_09_cart_box.png",
  "monster_10_room_distorter.png": "/assets/story/chapter1/characters/monster_10_room_distorter.png",
  "portrait_hobanwoo.svg": "/assets/story/chapter1/characters/hobanwoo_pose_neutral.png",
  "portrait_system.svg": "/assets/story/chapter1/ui/portrait_system.svg",
  "prologue_academic_systems_star.png": "/assets/story/chapter1/illustrations/prologue_academic_systems_star.png",
  "prologue_attendance_chase.png": "/assets/story/chapter1/illustrations/prologue_attendance_chase.png",
  "prologue_cheomseongdae_core.png": "/assets/story/chapter1/illustrations/prologue_cheomseongdae_core.png",
  "prologue_classroom_guide_star.png": "/assets/story/chapter1/illustrations/prologue_classroom_guide_star.png",
  "prologue_confusion_uploaded.png": "/assets/story/chapter1/illustrations/prologue_confusion_uploaded.png",
  "prologue_entrance_crowd.png": "/assets/story/chapter1/illustrations/prologue_entrance_crowd.png",
  "prologue_exam_anxiety_uploaded.png": "/assets/story/chapter1/illustrations/prologue_exam_anxiety_uploaded.png",
  "prologue_fragment_attendance_drone.png": "/assets/story/chapter1/illustrations/prologue_fragment_attendance_drone.png",
  "prologue_fragment_coords_distorter.png": "/assets/story/chapter1/illustrations/prologue_fragment_coords_distorter.png",
  "prologue_fragment_login_watcher.png": "/assets/story/chapter1/illustrations/prologue_fragment_login_watcher.png",
  "prologue_fragment_notice_drone.png": "/assets/story/chapter1/illustrations/prologue_fragment_notice_drone.png",
  "prologue_hobanwoo_hall.png": "/assets/story/chapter1/illustrations/prologue_hobanwoo_hall.png",
  "prologue_notice_burst.png": "/assets/story/chapter1/illustrations/prologue_notice_burst.png",
  "prologue_pressure_rocks.png": "/assets/story/chapter1/illustrations/prologue_pressure_rocks.png",
  "prologue_student_id_check.png": "/assets/story/chapter1/illustrations/prologue_student_id_check.png",
  "prologue_temp_academic_systems.svg": "/assets/story/chapter1/illustrations/prologue_academic_systems_star.png",
  "prologue_temp_classroom_arrows.svg": "/assets/story/chapter1/illustrations/prologue_classroom_guide_star.png",
  "prologue_temp_student_id.svg": "/assets/story/chapter1/illustrations/prologue_student_id_check.png",
  "prologue_wrong_coords.png": "/assets/story/chapter1/illustrations/prologue_wrong_coords.png",
  "prologue_wrong_coords_uploaded.png": "/assets/story/chapter1/illustrations/prologue_wrong_coords_uploaded.png",
  "prologue_wrong_coords_v3.png": "/assets/story/chapter1/illustrations/prologue_wrong_coords_v3.png",
  "story_attendance_stamp.png": "/assets/story/chapter1/illustrations/story_attendance_stamp.png",
  "story_notice_arrival.png": "/assets/story/chapter1/illustrations/story_notice_arrival.png",
  "story_notice_letter.svg": "/assets/story/chapter1/illustrations/story_notice_letter.svg",
  "story_student_card_glow.png": "/assets/story/chapter1/characters/story_student_card_normal.png",
  "story_student_card_normal.png": "/assets/story/chapter1/characters/story_student_card_normal.png",
};

export function createChapter1StoryEmbeddedAssets(): Record<string, string> {
  const assets: Record<string, string> = { ...CHAPTER1_STORY_ASSETS };
  for (const [name, value] of Object.entries(CHAPTER1_STORY_ASSETS)) {
    assets[`assets/${name}`] = value;
  }
  return assets;
}

export function rewriteChapter1StoryAssetReferences(source: string): string {
  return source.replace(/assets\/([^"')\s]+\.(?:png|webp|jpe?g|svg))/gi, (full, fileName: string) => {
    return CHAPTER1_STORY_ASSETS[fileName] ?? full;
  });
}
